# Tugboat configuration to replicate theoretical production infrastructure.
services:
  # Varnish in front of the entire stack.
  varnish:
    image: tugboatqa/varnish
    default: true
    commands:
      build:
        - echo 'neat.'
  # Nginx is behind Varnish and in front of Apache.
  nginx:
    image: tugboatqa/nginx
  # Use PHP 7.3 with Apache.
  apache-php:
    image: tugboatqa/php:7.3-apache
  # For MySQL, use Percona 5.6.
  mysql:
    image: tugboatqa/percona:5.6
  # Memcache is in place for Drupal cache.
  memcached:
    image: tugboatqa/memcached
